// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gindemo/webook/comment/grpc"
	"gindemo/webook/comment/ioc"
	"gindemo/webook/comment/repository"
	"gindemo/webook/comment/repository/dao"
	"gindemo/webook/comment/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Init() *App {
	loggerV1 := ioc.InitLogger()
	db := ioc.InitDB(loggerV1)
	commentDAO := dao.NewCommentDAO(db)
	commentRepository := repository.NewCommentRepo(loggerV1, commentDAO)
	commentService := service.NewCommentSvc(commentRepository)
	commentServiceServer := grpc.NewGrpcServer(commentService)
	server := ioc.InitGRPCxServer(commentServiceServer)
	app := &App{
		server: server,
	}
	return app
}

// wire.go:

var serviceProviderSet = wire.NewSet(dao.NewCommentDAO, repository.NewCommentRepo, service.NewCommentSvc, grpc.NewGrpcServer)

var thirdProvider = wire.NewSet(ioc.InitLogger, ioc.InitDB)
