// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gindemo/webook/api/proto/gen/account/v1"
	"gindemo/webook/api/proto/gen/payment/v1"
	"gindemo/webook/reward/ioc"
	"gindemo/webook/reward/repository"
	"gindemo/webook/reward/repository/cache"
	"gindemo/webook/reward/repository/dao"
	"gindemo/webook/reward/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitWechatNativeSvc(pclient pmtv1.WechatPaymentServiceClient, aclient accountv1.AccountServiceClient) *service.WechatNativeRewardService {
	gormDB := InitTestDB()
	rewardDAO := dao.NewRewardGORMDAO(gormDB)
	cmdable := InitRedis()
	rewardCache := cache.NewRewardRedisCache(cmdable)
	rewardRepository := repository.NewRewardRepository(rewardDAO, rewardCache)
	loggerV1 := ioc.InitLogger()
	wechatNativeRewardService := service.NewWechatNativeRewardService(pclient, rewardRepository, loggerV1, aclient)
	return wechatNativeRewardService
}

// wire.go:

var thirdPartySet = wire.NewSet(InitTestDB, ioc.InitLogger, InitRedis)
