apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-record-service
spec:
#   三个副本
  replicas: 3
  selector:
    matchLabels:
      app: webook-record
  template:
    metadata:
      labels:
        app: webook-record
    spec:
      containers:
        - name: webook-record
          image: smiling77877/webook:v0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
