// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"gindemo/webook/account/grpc"
	"gindemo/webook/account/repository"
	"gindemo/webook/account/repository/dao"
	"gindemo/webook/account/service"
)

// Injectors from wire.go:

func InitAccountService() *grpc.AccountServiceServer {
	gormDB := InitTestDB()
	accountDAO := dao.NewCreditGORMDAO(gormDB)
	accountRepository := repository.NewAccountRepository(accountDAO)
	accountService := service.NewAccountService(accountRepository)
	accountServiceServer := grpc.NewAccountServiceServer(accountService)
	return accountServiceServer
}
